<?php

namespace AppBundle\Repository;

/**
 * CotisationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CotisationRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param $annee
     * @return mixed
     * @throws \Doctrine\ORM\NoResultException
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function calculMontant($annee)
    {
        return $this->createQueryBuilder('c')
                    ->select('sum(c.montantSansFrais)')
                    ->where('c.annee = :annee')
                    ->setParameter('annee', $annee)
                    ->getQuery()->getSingleScalarResult()
            ;
    }
}
