<?php

namespace AppBundle\Repository;

/**
 * DistrictRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DistrictRepository extends \Doctrine\ORM\EntityRepository
{
    public function liste()
    {
        return $this->createQueryBuilder('d')->orderBy('d.nom', 'ASC');
    }

    public function findByRegion($slug)
    {
        return $this->createQueryBuilder('d')
                    ->leftJoin('d.region', 'r')
                    ->where('r.slug = :region')
                    ->orderBy('d.nom', 'ASC')
                    ->setParameter('region', $slug)
                    ->getQuery()->getResult()
            ;
    }

    public function getDistrictNombre($region= null)
    {
        if (!$region){
            return $this->createQueryBuilder('d')
                ->select('count(d.id)')
                ->getQuery()->getSingleScalarResult()
                ;
        }else{
            return $this->createQueryBuilder('d')
                ->select('count(d.id)')
                ->where('d.region = :region')
                ->setParameter('region', $region)
                ->getQuery()->getSingleScalarResult()
                ;
        }
    }
}
