<?php

namespace AppBundle\Repository;

/**
 * FonctionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FonctionsRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param $string
     * @return mixed
     * @throws \Doctrine\ORM\NoResultException
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function findByLibelle($string)
    {
        return $this->createQueryBuilder('f')
                    ->where('f.libelle LIKE :string')
                    ->setParameter('string', $string)
                    ->getQuery()->getResult()
            ;
    }
}
