<?php

namespace AppBundle\Repository;

/**
 * FonctionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FonctionsRepository extends \Doctrine\ORM\EntityRepository
{

}
