<?php

namespace AppBundle\Repository;

/**
 * PaiementsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaiementsRepository extends \Doctrine\ORM\EntityRepository
{
}
