<?php

namespace AppBundle\Repository;

/**
 * ScoutDeletedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ScoutDeletedRepository extends \Doctrine\ORM\EntityRepository
{
}
