<?php

namespace AppBundle\Repository;

/**
 * StatutRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatutRepository extends \Doctrine\ORM\EntityRepository
{
    public function liste()
    {
        return $this->createQueryBuilder('s')->orderBy('s.libelle', 'DESC');
    }
}
